### ISSUE TITLE
When launching multiple instances I get a error

### ISSUE THREAD

**Issue by FinickySpider** [FliiFe/Agar.io-bot-desktop-app#5]
When I attempt to launch multiple instances of this I get the following error:
![error](https://cloud.githubusercontent.com/assets/8377070/10057303/72fc108e-61f4-11e5-94fc-efcf5649ee3a.png)

The program will still continue to load up afterwords but with no bot selections anymore (specifically the feed bot which I'm trying to use). Although the first instance of the program works fine. I see some errors in the console that seem to talk about a failure to move some cache files around from appdata (which I'm guessing may be in use by the first instance still?) I'm running windows 7 64 Bit. Let me know if you need any other information.

**Comment by FinickySpider** [comment]
I also noticed this in the console:
![error2](https://cloud.githubusercontent.com/assets/8377070/10058214/2cbe0fe6-61f9-11e5-8610-fe0fa167ed14.PNG)

**Comment by bIack** [comment]
I've noticed these exact launch errors while tying to launch multiple clients..

**Comment by FliiFe** [comment]
Okay this is normal. I'll try to post a fix before the end of the week.
Can you tell me what happens after the error happens ? What do you mean by
"no bot selection" ?
Is the normal AposBot working fine ?
Le 23 sept. 2015 10:15 PM, "FinickySpider" <notifications@github.com> a
écrit :

**Comment by FliiFe** [comment]
The second issue is more problematic. The launcher (that includes all the
functions to make the bot) is loaded after the bot itself, I'll have a look
at it. Does this happens if you launch only one instance ?

**Comment by FliiFe** [comment]
Also, did you use the packaged version (in releases) ? It's not up-to-date, but i will soon upload the new version (which will probably be outdated one day later)...

**Comment by FinickySpider** [comment]
The aposbot always functions.

At first I thought the feeding bot just wouldn't load on the second instance but I did a little more testing and it seems for about every 3 instances I launch one will have all the bots. Here's what I mean.

On my 1st launch:
![er](https://cloud.githubusercontent.com/assets/8377070/10107027/15a5f38a-636d-11e5-9ba8-5a476e05e240.PNG)
You can see I can't select the feed bot. If I keep relaunching eventually I'll get a few that work.

On my 4th launch:
![er1](https://cloud.githubusercontent.com/assets/8377070/10107092/911ebc18-636d-11e5-9864-2df555ba7967.PNG)

I don't use github a lot but I believe I just hit the "download as zip" Button.

Let me know if you want me to post some screenshots of my console or anything else that might be helpful!

**Comment by FliiFe** [comment]
Okay i'm going to try an other approach of the bot integration.

"Download as zip" button is fine, that's the proper way to use this project if you don't have git installed

**Comment by FinickySpider** [comment]
Sounds good, I'll be here most the day if you need any other information. 

I wanted to ask if you plan on adding support for other scripts (not bots but things like OGARio by szymy) and if it's possible to launch the client using a proxy? Thanks!

**Comment by FliiFe** [comment]
The new approach I'm going to use will be more flexible therefore you will be able to use your own file as bot.
I'm thinking about something like
```
Agar.io-bot-desktop-app/
    public/
        dist/
        scripts/
            //All the files here with .js exptension will be loaded, subdirectories excluded, and maybe file containing "disabled" in their name will be excluded.
        user
    .gitignore
    LICENSE
    REAMDME.md
    main.js
    package.json
    start.bat
    start.sh
```

**Comment by FinickySpider** [comment]
That looks great! Super easy.

**Comment by FliiFe** [comment]
Okay I pushed a commit, but the original issue is still unfixed.

**Comment by FinickySpider** [comment]
Okay, seems to crash on startup now. I see the console and briefly the main window and then it crashes. I'll fool around with it some more.

**Comment by FliiFe** [comment]
You can try to replace `exit` by `pause` in start.bat to see log

**Comment by FinickySpider** [comment]
Oh actually that stopped it from crashing. I think the exit command in "start.bat" was closing the console and then that would close the main window. Same thing happens if I exit out of the console normally. Let me test some scripts.

**Comment by FinickySpider** [comment]
Okay I got it running, threw some scripts in to the scripts folder. It's still not loading the feed bot and the OGARio script didn't seem to work either.

**Comment by FliiFe** [comment]
Did you leave "bot.user.js" there ? It can interfer.
Also, I know this is dumb, but in Alphabetical order, launcher ***needs*** to be before the feedbot.
I'll have a look at OGARio scripts since I don't know them.

**Comment by FliiFe** [comment]
Okay make sure to remove every other scripts before using ogario script. You can disable them by adding `disabled` in its name (/!\ Case sensitive /!\)

**Comment by FinickySpider** [comment]
Okay I tried with just "launcher.user.js" and "zFeedingBot.user.js" in the scripts directory. Still not seeing the feedbot.

**Comment by FliiFe** [comment]
Can you send me the log (via pastie or pastebin olease, not directly here) ?

**Comment by FinickySpider** [comment]
Yup, here you go: http://pastebin.com/yMMKfxza

**Comment by FliiFe** [comment]
O_o now I remember. The feedbot has a dependency. You can download it here : http://www.parsecdn.com/js/parse-1.5.0.min.js

**Comment by FliiFe** [comment]
And maybe knowing that the filename doesn't need to be zFeedBot.user js but FeedBot.user.js (or whatever you call it)

**Comment by FinickySpider** [comment]
I put the z behind feedbot because otherwise feedbot would execute before launcher... Also I downloaded the parse-1.5.0.min.js file. I still don't see the feedbot. =/

**Comment by FliiFe** [comment]
Can you send me the new log again ?

**Comment by FinickySpider** [comment]
See my last post.

**Comment by FliiFe** [comment]
I meant the log after adding the parse dependency

**Comment by FinickySpider** [comment]
It was the new log after adding the parse dependency. I edited my post above. I also ran it a few times and one of the times the feeding bot loaded. I saved a log of the failed instance and the successful instance for comparison.

Fail: http://pastebin.com/7Yb2PwaR

Sucsess: http://pastebin.com/kQ6SCU22

**Comment by FliiFe** [comment]
I think I understood why. I'll try to post a fix tomorrow.

**Comment by FliiFe** [comment]
And I'll try to fix the initial issue at the same time.

**Comment by FinickySpider** [comment]
Alright Thanks!

**Comment by FliiFe** [comment]
I need an advice. Does the first window (with username choice) seems usefull to you (knowing it will work only with AposBot with a specific file name) ?
I can't decide to remove it or not.

**Comment by FliiFe** [comment]
I think I'm going to remove it as it is not really useful now that user can choose it scripts

**Comment by FliiFe** [comment]
All the issues above should be resolved by the last commit (3cc37cf40ebaaa35faacf2e62efab4b5b0ffa5fd)

**Comment by FinickySpider** [comment]
Trying to launch I get this error:
![nudkenl](https://cloud.githubusercontent.com/assets/8377070/10119501/7fdec094-644c-11e5-949c-351e86af2067.png)
And the console is empty.

**Comment by FinickySpider** [comment]
I added "call npm install portscanner" to the start.bat file. Everything is working now! Thanks!

**Comment by FinickySpider** [comment]
I'm interested in talking a bit more about this and I have a few somewhat off topic questions. Anyway I could get a email or other contact information?

**Comment by FliiFe** [comment]
I don't want to share my email publicly, but if you give yours, I'll send you mine.
Off topic questions are always interesting :)
